restaurants/urls.py
from django.conf.urls import url
from . import views

app_name = 'restaurants'

urlpatterns = [

	url(r'^$', views.index, name='index'),

	url(r'^(?P<location_id>[0-9]+)/$', views.detail, name='detail')
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^restaurants/', include('restaurants.urls')),

]

restaurants/models.py
from django.db import models

# Create your models here.

class Location(models.Model):

	location_name = models.CharField(max_length=50)
	postal_code = models.IntegerField()

	def __str__(self):
		return self.location_name + ' , ' + str(self.postal_code)

class Restaurant(models.Model):
	restaurant_location = models.ForeignKey(Location, on_delete=models.CASCADE)
	restaurant_name = models.CharField(max_length=50)
	restaurant_description = models.CharField(max_length=200)
	restaurant_link = models.URLField()
	
	#restaurant_logo = models.

	def __str__(self):
		return self.restaurant_name

restaurants/views.py
from django.shortcuts import render, get_object_or_404
from . models import Location

def index(request):
	all_locations = Location.objects.all().order_by('location_name')
	context = {'all_locations' : all_locations}
	return render(request,'restaurants/index.html',context)

def detail(request,location_id):
	#try:
	#	location = Location.objects.get(pk=location_id)
	#except Location.DoesNotExist:
	#	raise Http404("Location is not in our Databse yet.")
	location = get_object_or_404(Location,pk=location_id)
	return render(request,'restaurants/detail.html',{'location':location})

restaurants/templates/restaurants/detail.html
<h1>
	Restaurants available in {{location.location_name}}
</h1>

<ul>
	{% for restaurant in location.restaurant_set.all %}
	<li> {{ restaurant.restaurant_name }} </li>
	{% endfor %}
</ul>

restaurants/templates/restaurants/index.html
{% if all_locations %}
	<h2>Locations to find Restaurants</h2>

	<ul>
		{% for location in all_locations %}

			<li><a href="{% url 'restaurants:detail' location.id %}">{{location.location_name}}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<h2>We are still working on it... </h2>
{% endif %}